const mongoose = require('mongoose');

const chatSessionSchema = mongoose.Schema({
    botId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Bot',
        required: true
    },
    clientSessionId: {
        type: String, 
        required: true,
        // This is a unique token generated by the widget to track an anonymous user's chat tab
    },
    messages: [
        {
            role: {
                type: String,
                enum: ['user', 'model', 'system'], // Using 'model' to align with Gemini's standard format
                required: true
            },
            content: {
                type: String,
                required: true
            },
            timestamp: {
                type: Date,
                default: Date.now
            }
        }
    ]
}, {
    timestamps: true
});

module.exports = mongoose.model('ChatSession', chatSessionSchema);
